require('dotenv').config();

module.exports = {
  apps: [
    {
      name: 'sandwich-1',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      pre_start: 'node bot/scripts/validate-env.js',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS || 'https://bsc-dataseed.binance.org,https://bsc-dataseed1.defibit.io',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: 50,
        MIN_PROFIT_USD: 0.10,
        GAS_PREMIUM_GWEI: 1.5,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        WALLET_ROTATION_TIME: 1800000,
        WALLET_ROTATION_TRADES: 50,
        MAX_ANOMALIES: 5,
        PROFIT_THRESHOLD: 0.05,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 500,
        SYNC_INTERVAL: 250,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        MIN_LIQUIDITY: 100000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 500000,
        FLASH_ENGINE_ADDRESS: process.env.FLASH_ENGINE_ADDRESS,
        NOTIFICATION_EMAIL: 'oceanby312@icloud.com',
        AUTO_WITHDRAW_THRESHOLD: 0.5,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10,
        CHAIN_ID: 56,
        // BSC DEX Routers
        PANCAKESWAP_ROUTER_V2: process.env.PANCAKESWAP_ROUTER_V2,
        BISWAP_ROUTER: process.env.BISWAP_ROUTER,
        APESWAP_ROUTER: process.env.APESWAP_ROUTER,
        BAKERYSWAP_ROUTER: process.env.BAKERYSWAP_ROUTER
      },
      error_file: 'logs/sandwich-1-error.log',
      out_file: 'logs/sandwich-1-out.log',
      log_file: 'logs/sandwich-1-combined.log',
      time: true
    },
    {
      name: 'sandwich-2',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_production: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: 50,
        MIN_PROFIT_USD: 0.10,
        GAS_PREMIUM_GWEI: 1.5,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        WALLET_ROTATION_TIME: 1800000,
        WALLET_ROTATION_TRADES: 50,
        MAX_ANOMALIES: 5,
        PROFIT_THRESHOLD: 0.05,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 500,
        SYNC_INTERVAL: 250,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        MIN_LIQUIDITY: 100000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 500000,
        FLASH_ENGINE_ADDRESS: process.env.FLASH_ENGINE_ADDRESS,
        NOTIFICATION_EMAIL: 'oceanby312@icloud.com',
        AUTO_WITHDRAW_THRESHOLD: 0.5,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10,
        CHAIN_ID: 56,
        PANCAKESWAP_ROUTER_V2: process.env.PANCAKESWAP_ROUTER_V2,
        BISWAP_ROUTER: process.env.BISWAP_ROUTER,
        APESWAP_ROUTER: process.env.APESWAP_ROUTER,
        BAKERYSWAP_ROUTER: process.env.BAKERYSWAP_ROUTER
      },
      error_file: 'logs/sandwich-2-error.log',
      out_file: 'logs/sandwich-2-out.log',
      log_file: 'logs/sandwich-2-combined.log',
      time: true
    },
    {
      name: 'sandwich-3',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: 35,
        MIN_PROFIT_USD: 0.08,
        GAS_PREMIUM_GWEI: 1.2,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        WALLET_ROTATION_TIME: process.env.WALLET_ROTATION_TIME,
        WALLET_ROTATION_TRADES: process.env.WALLET_ROTATION_TRADES,
        MAX_ANOMALIES: process.env.MAX_ANOMALIES,
        PROFIT_THRESHOLD: 0.04,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 750,
        SYNC_INTERVAL: 400,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        MIN_LIQUIDITY: 75000,
        MAX_SLIPPAGE: 2.5,
        GAS_LIMIT: 500000,
        CHAIN_ID: 56,
        FLASH_ENGINE_ADDRESS: process.env.FLASH_ENGINE_ADDRESS,
        PANCAKESWAP_ROUTER_V2: process.env.PANCAKESWAP_ROUTER_V2,
        BISWAP_ROUTER: process.env.BISWAP_ROUTER,
        APESWAP_ROUTER: process.env.APESWAP_ROUTER,
        BAKERYSWAP_ROUTER: process.env.BAKERYSWAP_ROUTER
      },
      error_file: 'logs/sandwich-3-error.log',
      out_file: 'logs/sandwich-3-out.log',
      log_file: 'logs/sandwich-3-combined.log',
      time: true,
      pre_start: 'node bot/scripts/check-dependencies.js'
    },
    {
      name: 'pancake-arbitrage',
      script: 'bot/pancake-arbitrage.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_PROFIT_USD: 0.15,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        GAS_LIMIT: 600000,
        FLASH_ENGINE_ADDRESS: process.env.FLASH_ENGINE_ADDRESS,
        PANCAKESWAP_ROUTER_V2: process.env.PANCAKESWAP_ROUTER_V2,
        PANCAKESWAP_FACTORY_V2: process.env.PANCAKESWAP_FACTORY_V2,
        SCAN_INTERVAL: 1000,
        CHAIN_ID: 56
      },
      error_file: 'logs/pancake-arbitrage-error.log',
      out_file: 'logs/pancake-arbitrage-out.log',
      log_file: 'logs/pancake-arbitrage-combined.log',
      time: true
    },
    {
      name: 'venus-liquidation',
      script: 'bot/venus-liquidation.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_PROFIT_USD: 0.50,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        GAS_LIMIT: 800000,
        VENUS_UNITROLLER: process.env.VENUS_UNITROLLER,
        SCAN_INTERVAL: 5000,
        CHAIN_ID: 56
      },
      error_file: 'logs/venus-liquidation-error.log',
      out_file: 'logs/venus-liquidation-out.log',
      log_file: 'logs/venus-liquidation-combined.log',
      time: true
    },
    {
      name: 'rpc-healthcheck',
      script: 'bot/rpcHealthCheck.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        CHAIN_ID: 56
      },
      error_file: 'logs/rpc-healthcheck-error.log',
      out_file: 'logs/rpc-healthcheck-out.log',
      log_file: 'logs/rpc-healthcheck-combined.log',
      time: true
    },
    {
      name: 'profit-monitor',
      script: 'bot/profitMonitor.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL || 'wss://bsc-mainnet.nodereal.io/ws/v1/your-api-key',
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS || 'https://bsc-dataseed.binance.org,https://bsc-dataseed1.defibit.io',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_PROFIT_USD: 0.10,
        GAS_PREMIUM_GWEI: 1.5,
        SCAN_INTERVAL: 1000,
        SYNC_INTERVAL: 500,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        MIN_LIQUIDITY: 100000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 500000,
        AUTO_WITHDRAW_THRESHOLD: 0.5,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        EMAIL_TO: process.env.EMAIL_TO,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10,
        CHAIN_ID: 56
      },
      error_file: 'logs/profit-monitor-error.log',
      out_file: 'logs/profit-monitor-out.log',
      log_file: 'logs/profit-monitor-combined.log',
      time: true
    },
    {
      name: 'profit-dashboard',
      script: 'dashboard/server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NETWORK: 'bsc',
        RPC_URL: process.env.RPC_URL || 'wss://bsc-mainnet.nodereal.io/ws/v1/your-api-key',
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS || 'https://bsc-dataseed.binance.org,https://bsc-dataseed1.defibit.io',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_PROFIT_USD: 0.10,
        GAS_PREMIUM_GWEI: 1.5,
        SCAN_INTERVAL: 1000,
        SYNC_INTERVAL: 500,
        MAX_GAS_PRICE: 20,
        MIN_GAS_PRICE: 5,
        MIN_LIQUIDITY: 100000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 500000,
        AUTO_WITHDRAW_THRESHOLD: 0.5,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        EMAIL_TO: process.env.EMAIL_TO,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10,
        CHAIN_ID: 56
      }
    }
  ]
}; 