require('dotenv').config();

module.exports = {
  apps: [
    {
      name: 'sandwich-1',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      pre_start: 'node bot/scripts/validate-env.js',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'polygon',
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS || 'https://polygon-rpc.com,https://rpc-mainnet.matic.network',
        FLASHBOTS_RELAY_URL: 'https://relay.flashbots.net',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: 25,
        MIN_PROFIT_USD: 0.05,
        GAS_PREMIUM_GWEI: 2.0,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        WALLET_ROTATION_TIME: 1800000,
        WALLET_ROTATION_TRADES: 50,
        MAX_ANOMALIES: 5,
        PROFIT_THRESHOLD: 0.05,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 1000,
        SYNC_INTERVAL: 500,
        MAX_GAS_PRICE: 1000,
        MIN_LIQUIDITY: 50000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 600000,
        FLASH_ENGINE_ADDRESS: process.env.FLASH_ENGINE_ADDRESS,
        NOTIFICATION_EMAIL: 'oceanby312@icloud.com',
        AUTO_WITHDRAW_THRESHOLD: 0.1,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10
      },
      error_file: 'logs/sandwich-1-error.log',
      out_file: 'logs/sandwich-1-out.log',
      log_file: 'logs/sandwich-1-combined.log',
      time: true
    },
    {
      name: 'sandwich-2',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_production: {
        NODE_ENV: 'production',
        NETWORK: 'polygon',
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        FLASHBOTS_RELAY_URL: 'https://relay.flashbots.net',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: 25,
        MIN_PROFIT_USD: 0.05,
        GAS_PREMIUM_GWEI: 2.0,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        WALLET_ROTATION_TIME: 1800000,
        WALLET_ROTATION_TRADES: 50,
        MAX_ANOMALIES: 5,
        PROFIT_THRESHOLD: 0.05,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 1000,
        SYNC_INTERVAL: 500,
        MAX_GAS_PRICE: 1000,
        MIN_LIQUIDITY: 50000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 600000,
        FLASH_ENGINE_ADDRESS: process.env.FLASH_ENGINE_ADDRESS,
        NOTIFICATION_EMAIL: 'oceanby312@icloud.com',
        AUTO_WITHDRAW_THRESHOLD: 0.1,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10
      },
      error_file: 'logs/sandwich-2-error.log',
      out_file: 'logs/sandwich-2-out.log',
      log_file: 'logs/sandwich-2-combined.log',
      time: true
    },
    {
      name: 'sandwich-3',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: process.env.NETWORK,
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        FLASHBOTS_RELAY_URL: process.env.FLASHBOTS_RELAY_URL,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: process.env.MIN_SWAP_USD * 0.7,
        MIN_PROFIT_USD: process.env.MIN_PROFIT_USD * 0.6,
        GAS_PREMIUM_GWEI: process.env.GAS_PREMIUM_GWEI * 0.8,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
        WALLET_ROTATION_TIME: process.env.WALLET_ROTATION_TIME,
        WALLET_ROTATION_TRADES: process.env.WALLET_ROTATION_TRADES,
        MAX_ANOMALIES: process.env.MAX_ANOMALIES,
        PROFIT_THRESHOLD: process.env.PROFIT_THRESHOLD * 0.7,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE
      },
      error_file: 'logs/sandwich-3-error.log',
      out_file: 'logs/sandwich-3-out.log',
      log_file: 'logs/sandwich-3-combined.log',
      time: true,
      pre_start: 'node bot/scripts/check-dependencies.js'
    },
    {
      name: 'sandwich-4',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: process.env.NETWORK,
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        FLASHBOTS_RELAY_URL: process.env.FLASHBOTS_RELAY_URL,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: process.env.MIN_SWAP_USD * 0.7,
        MIN_PROFIT_USD: process.env.MIN_PROFIT_USD * 0.6,
        GAS_PREMIUM_GWEI: process.env.GAS_PREMIUM_GWEI * 0.8,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
        WALLET_ROTATION_TIME: process.env.WALLET_ROTATION_TIME,
        WALLET_ROTATION_TRADES: process.env.WALLET_ROTATION_TRADES,
        MAX_ANOMALIES: process.env.MAX_ANOMALIES,
        PROFIT_THRESHOLD: process.env.PROFIT_THRESHOLD * 0.7,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE
      },
      error_file: 'logs/sandwich-4-error.log',
      out_file: 'logs/sandwich-4-out.log',
      log_file: 'logs/sandwich-4-combined.log',
      time: true,
      pre_start: 'node bot/scripts/check-dependencies.js'
    },
    {
      name: 'sandwich-5',
      script: 'bot/sandwich.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: process.env.NETWORK,
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        FLASHBOTS_RELAY_URL: process.env.FLASHBOTS_RELAY_URL,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: process.env.MIN_SWAP_USD * 0.7,
        MIN_PROFIT_USD: process.env.MIN_PROFIT_USD * 0.6,
        GAS_PREMIUM_GWEI: process.env.GAS_PREMIUM_GWEI * 0.8,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
        WALLET_ROTATION_TIME: process.env.WALLET_ROTATION_TIME,
        WALLET_ROTATION_TRADES: process.env.WALLET_ROTATION_TRADES,
        MAX_ANOMALIES: process.env.MAX_ANOMALIES,
        PROFIT_THRESHOLD: process.env.PROFIT_THRESHOLD * 0.7,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE
      },
      error_file: 'logs/sandwich-5-error.log',
      out_file: 'logs/sandwich-5-out.log',
      log_file: 'logs/sandwich-5-combined.log',
      time: true,
      pre_start: 'node bot/scripts/check-dependencies.js'
    },
    {
      name: 'liquidation-scanner',
      script: 'bot/liquidation.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: process.env.NETWORK,
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        FLASHBOTS_RELAY_URL: process.env.FLASHBOTS_RELAY_URL,
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_SWAP_USD: process.env.MIN_SWAP_USD * 0.7,
        MIN_PROFIT_USD: process.env.MIN_PROFIT_USD * 0.6,
        GAS_PREMIUM_GWEI: process.env.GAS_PREMIUM_GWEI * 0.8,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
        WALLET_ROTATION_TIME: process.env.WALLET_ROTATION_TIME,
        WALLET_ROTATION_TRADES: process.env.WALLET_ROTATION_TRADES,
        MAX_ANOMALIES: process.env.MAX_ANOMALIES,
        PROFIT_THRESHOLD: process.env.PROFIT_THRESHOLD * 0.7,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE
      },
      error_file: 'logs/liquidation-scanner-error.log',
      out_file: 'logs/liquidation-scanner-out.log',
      log_file: 'logs/liquidation-scanner-combined.log',
      time: true,
      pre_start: 'node bot/scripts/check-dependencies.js'
    },
    {
      name: 'rpc-healthcheck',
      script: 'bot/rpcHealthCheck.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: process.env.NETWORK,
        RPC_URL: process.env.RPC_URL,
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS,
        SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE
      },
      error_file: 'logs/rpc-healthcheck-error.log',
      out_file: 'logs/rpc-healthcheck-out.log',
      log_file: 'logs/rpc-healthcheck-combined.log',
      time: true
    },
    {
      name: 'health-monitor',
      script: 'bot/healthMonitor.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: process.env.NETWORK,
        SLACK_WEBHOOK_URL: process.env.SLACK_WEBHOOK_URL,
        SCAN_INTERVAL: 10000,
        SYNC_INTERVAL: 5000,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE
      },
      error_file: 'logs/health-monitor-error.log',
      out_file: 'logs/health-monitor-out.log',
      log_file: 'logs/health-monitor-combined.log',
      time: true
    },
    {
      name: 'profit-monitor',
      script: 'bot/profitMonitor.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NETWORK: 'polygon',
        RPC_URL: process.env.RPC_URL || 'wss://polygon-mainnet.g.alchemy.com/v2/your-api-key',
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS || 'https://polygon-rpc.com,https://rpc-mainnet.matic.network',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_PROFIT_USD: 0.05,
        GAS_PREMIUM_GWEI: 2.0,
        SCAN_INTERVAL: 1000,
        SYNC_INTERVAL: 500,
        RETENTION_PERIOD: process.env.RETENTION_PERIOD,
        MAX_FILE_SIZE: process.env.MAX_FILE_SIZE,
        MAX_GAS_PRICE: 1000,
        MIN_LIQUIDITY: 50000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 600000,
        AUTO_WITHDRAW_THRESHOLD: 0.1,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        EMAIL_TO: process.env.EMAIL_TO,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10
      },
      error_file: 'logs/profit-monitor-error.log',
      out_file: 'logs/profit-monitor-out.log',
      log_file: 'logs/profit-monitor-combined.log',
      time: true
    },
    {
      name: 'profit-dashboard',
      script: 'dashboard/server.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NETWORK: 'polygon',
        RPC_URL: process.env.RPC_URL || 'wss://polygon-mainnet.g.alchemy.com/v2/your-api-key',
        FALLBACK_RPC_URLS: process.env.FALLBACK_RPC_URLS || 'https://polygon-rpc.com,https://rpc-mainnet.matic.network',
        BOT_PRIVATE_KEY: process.env.BOT_PRIVATE_KEY,
        MIN_PROFIT_USD: 0.05,
        GAS_PREMIUM_GWEI: 2.0,
        SCAN_INTERVAL: 1000,
        SYNC_INTERVAL: 500,
        MAX_GAS_PRICE: 1000,
        MIN_LIQUIDITY: 50000,
        MAX_SLIPPAGE: 2.0,
        GAS_LIMIT: 600000,
        AUTO_WITHDRAW_THRESHOLD: 0.1,
        PLATFORM_WALLET: process.env.PLATFORM_WALLET,
        COLD_WALLET_ADDRESS: process.env.COLD_WALLET_ADDRESS,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        EMAIL_TO: process.env.EMAIL_TO,
        WS_RECONNECT_INTERVAL: 5000,
        MAX_RECONNECT_ATTEMPTS: 10
      }
    }
  ]
}; 